# Citizens CMD Plugin
# by Mateus Moreira @LichtHund & Maintained by HexedHero
# Wiki: https://github.com/HexedHero/CitizensCMD/wiki
# GitHub: https://github.com/HexedHero/CitizensCMD
# Spigot: https://www.spigotmc.org/resources/30224/

main: me.mattstudios.citizenscmd.CitizensCMD
version: ${project.version}
name: CitizensCMD
website: https://spigotmc.org/resources/30224/
authors: [Mateus Moreira, HexedHero]
softdepend: [Citizens, PlaceholderAPI, Vault]
api-version: 1.13

commands:
  npcmd:
    description: Main command for help

permissions:
  citizenscmd.use:
    description: Allows player to click NPC.
    default: true
  citizenscmd.help:
    default: op
  citizenscmd.add:
    default: op
  citizenscmd.list:
    default: op
  citizenscmd.cooldown:
    default: op
  citizenscmd.price:
    default: op
  citizenscmd.reload:
    default: op
  citizenscmd.permission:
    default: op
  citizenscmd.remove:
    default: op
  citizenscmd.edit:
    default: op
  citizenscmd.bypass:
    default: false